import type {
  User,
  Screen,
  ScreenGroup,
  Media,
  Campaign,
  Playlist,
  Schedule,
  Advertiser,
  Zone,
  AdBooking,
  Notification,
  PlayLog,
  AnalyticsSummary,
  ActivityItem,
  ClientPayment,
  SupportTicket,
} from "@/types";

const now = new Date();
const hoursAgo = (h: number) => new Date(now.getTime() - h * 3600000);

export const mockUser: User = {
  id: "user-1",
  name: "Rajesh Kumar",
  email: "rajesh@adflow.in",
  role: "admin",
  avatar: undefined,
  createdAt: now,
  updatedAt: now,
};

export const mockClientUser: User = {
  id: "user-client-1",
  name: "Priya Reddy",
  email: "priya@heritagefoods.ap.in",
  role: "advertiser",
  advertiserId: "adv-1",
  createdAt: now,
  updatedAt: now,
};

export const mockScreens: Screen[] = [
  {
    id: "scr-1",
    name: "Vizag RK Beach LED",
    pairingCode: "A7KD92",
    location: "RK Beach Road, Visakhapatnam",
    city: "Visakhapatnam",
    zoneId: "zone-vizag",
    status: "online",
    resolution: "3840x2160",
    currentPlaylistId: "pl-1",
    lastSeen: hoursAgo(0.1),
    health: { cpu: 34, ram: 62, storage: 45 },
    createdAt: hoursAgo(720),
  },
  {
    id: "scr-2",
    name: "Vijayawada Benz Circle",
    pairingCode: "B3XM45",
    location: "Benz Circle, Vijayawada",
    city: "Vijayawada",
    zoneId: "zone-vijayawada",
    status: "online",
    resolution: "1920x1080",
    currentPlaylistId: "pl-2",
    lastSeen: hoursAgo(0.2),
    health: { cpu: 28, ram: 55, storage: 38 },
    createdAt: hoursAgo(500),
  },
  {
    id: "scr-3",
    name: "Guntur Brodipet Hub",
    pairingCode: "C9PQ71",
    location: "Brodipet Main Road, Guntur",
    city: "Guntur",
    zoneId: "zone-guntur",
    status: "offline",
    resolution: "1920x1080",
    lastSeen: hoursAgo(48),
    health: { cpu: 0, ram: 0, storage: 72 },
    createdAt: hoursAgo(300),
  },
  {
    id: "scr-4",
    name: "Tirupati Bus Stand",
    pairingCode: "D2RT88",
    location: "APSRTC Bus Stand, Tirupati",
    city: "Tirupati",
    zoneId: "zone-tirupati",
    status: "online",
    resolution: "2560x1440",
    currentPlaylistId: "pl-1",
    lastSeen: hoursAgo(0.05),
    health: { cpu: 41, ram: 68, storage: 52 },
    createdAt: hoursAgo(200),
  },
  {
    id: "scr-5",
    name: "Amaravati Capital Display",
    pairingCode: "E5UV33",
    location: "Seed Access Road, Amaravati",
    city: "Amaravati",
    zoneId: "zone-amaravati",
    status: "online",
    resolution: "3840x2160",
    currentPlaylistId: "pl-3",
    lastSeen: hoursAgo(0.3),
    health: { cpu: 22, ram: 48, storage: 61 },
    createdAt: hoursAgo(150),
  },
];

export const mockScreenGroups: ScreenGroup[] = [
  {
    id: "grp-1",
    name: "Coastal Andhra",
    description: "Screens across Visakhapatnam and Kakinada corridor",
    screenIds: ["scr-1"],
    playlistId: "pl-1",
    createdAt: hoursAgo(100),
  },
  {
    id: "grp-2",
    name: "Capital Region",
    description: "Vijayawada, Guntur and Amaravati cluster",
    screenIds: ["scr-2", "scr-3", "scr-5"],
    playlistId: "pl-2",
    createdAt: hoursAgo(80),
  },
];

export const mockMedia: Media[] = [
  {
    id: "med-1",
    name: "Sankranti Sale Banner",
    type: "image",
    url: "/placeholder-media.jpg",
    size: 2450000,
    duration: 10,
    tags: ["retail", "festival"],
    category: "Promotions",
    uploadedBy: "user-1",
    createdAt: hoursAgo(24),
  },
  {
    id: "med-2",
    name: "Ugadi Launch Video",
    type: "video",
    url: "/placeholder-media.jpg",
    size: 45000000,
    duration: 30,
    tags: ["product", "launch"],
    category: "Brand",
    uploadedBy: "user-1",
    createdAt: hoursAgo(48),
  },
  {
    id: "med-3",
    name: "AP Tourism Poster",
    type: "poster",
    url: "/placeholder-media.jpg",
    size: 5200000,
    duration: 15,
    tags: ["tourism", "andhra"],
    uploadedBy: "user-1",
    createdAt: hoursAgo(72),
  },
  {
    id: "med-client-1",
    name: "Heritage Ugadi Banner",
    type: "image",
    url: "/placeholder-media.jpg",
    size: 2100000,
    duration: 10,
    tags: ["festival", "ugadi", "heritage"],
    uploadedBy: "user-client-1",
    advertiserId: "adv-1",
    createdAt: hoursAgo(12),
  },
  {
    id: "med-client-2",
    name: "Summer Sale Telugu Video",
    type: "video",
    url: "/placeholder-media.jpg",
    size: 38000000,
    duration: 30,
    tags: ["sale", "telugu", "summer"],
    uploadedBy: "user-client-1",
    advertiserId: "adv-1",
    createdAt: hoursAgo(36),
  },
];

export const mockPlaylists: Playlist[] = [
  {
    id: "pl-1",
    name: "Retail Rotation AP",
    items: [
      { mediaId: "med-1", duration: 10, order: 0 },
      { mediaId: "med-2", duration: 30, order: 1 },
      { mediaId: "med-3", duration: 15, order: 2 },
    ],
    loop: true,
    shuffle: false,
    createdAt: hoursAgo(100),
  },
  {
    id: "pl-2",
    name: "Brand Awareness Telugu",
    items: [
      { mediaId: "med-2", duration: 30, order: 0 },
      { mediaId: "med-1", duration: 10, order: 1 },
    ],
    loop: true,
    shuffle: true,
    createdAt: hoursAgo(80),
  },
  {
    id: "pl-3",
    name: "Capital Region Premium",
    items: [{ mediaId: "med-2", duration: 30, order: 0 }],
    loop: true,
    shuffle: false,
    createdAt: hoursAgo(60),
  },
];

export const mockCampaigns: Campaign[] = [
  {
    id: "camp-1",
    name: "Sankranti Mega Sale 2026",
    description: "Statewide Sankranti promotion across Andhra Pradesh",
    advertiserId: "adv-1",
    priority: 1,
    status: "active",
    startDate: hoursAgo(168),
    endDate: new Date(now.getTime() + 30 * 86400000),
    screenIds: ["scr-1", "scr-2", "scr-4"],
    playlistId: "pl-1",
    createdAt: hoursAgo(200),
  },
  {
    id: "camp-2",
    name: "AP Tourism Summer",
    advertiserId: "adv-2",
    priority: 2,
    status: "scheduled",
    startDate: new Date(now.getTime() + 7 * 86400000),
    endDate: new Date(now.getTime() + 60 * 86400000),
    screenIds: ["scr-5"],
    playlistId: "pl-3",
    createdAt: hoursAgo(50),
  },
];

export const mockSchedules: Schedule[] = [
  {
    id: "sch-1",
    campaignId: "camp-1",
    startTime: "09:00",
    endTime: "21:00",
    days: ["mon", "tue", "wed", "thu", "fri", "sat", "sun"],
    createdAt: hoursAgo(100),
  },
];

export const mockZones: Zone[] = [
  { id: "zone-vizag", name: "Visakhapatnam", city: "Visakhapatnam", screenIds: ["scr-1"], playlistId: "pl-1", hourlyRate: 3500, createdAt: hoursAgo(200) },
  { id: "zone-vijayawada", name: "Vijayawada", city: "Vijayawada", screenIds: ["scr-2"], playlistId: "pl-2", hourlyRate: 3000, createdAt: hoursAgo(200) },
  { id: "zone-guntur", name: "Guntur", city: "Guntur", screenIds: ["scr-3"], hourlyRate: 2500, createdAt: hoursAgo(200) },
  { id: "zone-tirupati", name: "Tirupati", city: "Tirupati", screenIds: ["scr-4"], playlistId: "pl-1", hourlyRate: 2800, createdAt: hoursAgo(200) },
  { id: "zone-amaravati", name: "Amaravati", city: "Amaravati", screenIds: ["scr-5"], playlistId: "pl-3", hourlyRate: 3200, createdAt: hoursAgo(200) },
];

export const mockAdvertisers: Advertiser[] = [
  {
    id: "adv-1",
    companyName: "Heritage Foods Ltd.",
    contactName: "Priya Reddy",
    email: "priya@heritagefoods.ap.in",
    phone: "+91 866 245 0100",
    address: "Autonagar, Vijayawada, Andhra Pradesh 520007",
    plan: "professional",
    planPrice: 24999,
    nextPaymentDue: new Date("2026-07-01"),
    budget: 5000000,
    budgetUsed: 1850000,
    maxAds: 10,
    activeAds: 3,
    zoneIds: ["zone-vizag", "zone-vijayawada", "zone-tirupati"],
    status: "active",
  },
  {
    id: "adv-2",
    companyName: "AP Tourism Development",
    contactName: "Srinivas Rao",
    email: "srinivas@aptourism.ap.gov.in",
    phone: "+91 40 2345 6200",
    address: "Tank Bund Road, Vijayawada, Andhra Pradesh 520010",
    plan: "enterprise",
    planPrice: 79999,
    nextPaymentDue: new Date("2026-07-01"),
    budget: 12000000,
    budgetUsed: 4200000,
    maxAds: 20,
    activeAds: 5,
    zoneIds: ["zone-vizag", "zone-amaravati", "zone-vijayawada"],
    status: "active",
  },
  {
    id: "adv-3",
    companyName: "Amaravati Retail Hub",
    contactName: "Kiran Babu",
    email: "kiran@amaravatiretail.in",
    phone: "+91 863 222 3300",
    address: "Labbipet, Vijayawada, Andhra Pradesh 520010",
    plan: "starter",
    planPrice: 7999,
    nextPaymentDue: new Date("2026-06-20"),
    budget: 500000,
    budgetUsed: 120000,
    maxAds: 3,
    activeAds: 1,
    zoneIds: ["zone-guntur"],
    status: "active",
  },
];

export const mockClientPayments: ClientPayment[] = [
  { id: "pay-adv1-1", advertiserId: "adv-1", amount: 24999, date: new Date("2026-06-01"), method: "UPI ·••• 4521", status: "paid", invoiceId: "inv-adv1-06" },
  { id: "pay-adv1-2", advertiserId: "adv-1", amount: 24999, date: new Date("2026-05-01"), method: "HDFC •••• 8820", status: "paid", invoiceId: "inv-adv1-05" },
  { id: "pay-adv2-1", advertiserId: "adv-2", amount: 79999, date: new Date("2026-06-01"), method: "NEFT — SBI", status: "paid", invoiceId: "inv-adv2-06" },
  { id: "pay-adv2-2", advertiserId: "adv-2", amount: 79999, date: new Date("2026-05-01"), method: "NEFT — SBI", status: "paid", invoiceId: "inv-adv2-05" },
  { id: "pay-adv3-1", advertiserId: "adv-3", amount: 7999, date: new Date("2026-05-15"), method: "UPI ·••• 9012", status: "paid", invoiceId: "inv-adv3-05" },
  { id: "pay-adv3-2", advertiserId: "adv-3", amount: 7999, date: new Date("2026-06-15"), method: "UPI ·••• 9012", status: "pending", invoiceId: "inv-adv3-06" },
];

export const mockSupportTickets: SupportTicket[] = [
  {
    id: "tkt-1",
    advertiserId: "adv-1",
    subject: "Invoice mismatch for June",
    message: "Our June invoice shows ₹26,499 but plan is ₹24,999. Please clarify.",
    category: "billing",
    status: "open",
    priority: "high",
    createdAt: hoursAgo(6),
  },
  {
    id: "tkt-2",
    advertiserId: "adv-2",
    subject: "Need to increase ad limit",
    message: "We want to run 8 more campaigns during Brahmotsavam season in Tirupati.",
    category: "ads",
    status: "in_progress",
    priority: "medium",
    createdAt: hoursAgo(24),
  },
  {
    id: "tkt-3",
    advertiserId: "adv-3",
    subject: "Payment failed on UPI",
    message: "June subscription payment failed. Can we retry or pay via bank transfer?",
    category: "billing",
    status: "open",
    priority: "high",
    createdAt: hoursAgo(12),
  },
  {
    id: "tkt-4",
    advertiserId: "adv-1",
    subject: "Screen not showing new ad",
    message: "Sankranti banner not playing on Vizag RK Beach screen since yesterday.",
    category: "technical",
    status: "resolved",
    priority: "medium",
    createdAt: hoursAgo(72),
    updatedAt: hoursAgo(48),
  },
];

const today = now.toISOString().split("T")[0];

export const mockAdBookings: AdBooking[] = [
  {
    id: "book-1",
    advertiserId: "adv-1",
    campaignId: "camp-1",
    title: "Sankranti Sale Banner",
    screenId: "scr-1",
    zoneId: "zone-vizag",
    date: today,
    startTime: "09:00",
    endTime: "12:00",
    cost: 10500,
    status: "confirmed",
    createdBy: "admin",
    createdAt: hoursAgo(48),
  },
  {
    id: "book-2",
    advertiserId: "adv-2",
    title: "AP Tourism Promo",
    screenId: "scr-1",
    zoneId: "zone-vizag",
    date: today,
    startTime: "12:00",
    endTime: "15:00",
    cost: 10500,
    status: "confirmed",
    createdBy: "admin",
    createdAt: hoursAgo(36),
  },
  {
    id: "book-3",
    advertiserId: "adv-1",
    title: "Heritage Dairy Ad",
    screenId: "scr-2",
    zoneId: "zone-vijayawada",
    date: today,
    startTime: "10:00",
    endTime: "13:00",
    cost: 9000,
    status: "confirmed",
    createdBy: "client",
    createdAt: hoursAgo(24),
  },
  {
    id: "book-4",
    advertiserId: "adv-2",
    title: "Amaravati Capital Tour",
    screenId: "scr-5",
    zoneId: "zone-amaravati",
    date: today,
    startTime: "14:00",
    endTime: "17:00",
    cost: 9600,
    status: "confirmed",
    createdBy: "client",
    createdAt: hoursAgo(12),
  },
];

export const mockNotifications: Notification[] = [
  {
    id: "notif-1",
    title: "Screen Offline",
    message: "Guntur Brodipet Hub went offline 2 hours ago",
    type: "warning",
    userId: "user-1",
    read: false,
    createdAt: hoursAgo(2),
  },
  {
    id: "notif-2",
    title: "Campaign Started",
    message: "Sankranti Mega Sale 2026 is now live on 3 screens",
    type: "success",
    userId: "user-1",
    read: false,
    createdAt: hoursAgo(5),
  },
  {
    id: "notif-3",
    title: "New Media Uploaded",
    message: "Ugadi Launch Video added to media library",
    type: "info",
    userId: "user-1",
    read: true,
    createdAt: hoursAgo(24),
  },
];

export const mockAnalytics: AnalyticsSummary = {
  totalScreens: 847,
  onlineScreens: 812,
  offlineScreens: 35,
  activeCampaigns: 28,
  scheduledCampaigns: 9,
  revenue: 28475000,
  todayPlays: 45892,
};

export const mockActivities: ActivityItem[] = [
  {
    id: "act-1",
    type: "screen",
    title: "Screen paired",
    description: "Tirupati Bus Stand linked successfully",
    timestamp: hoursAgo(1),
    user: "Rajesh Kumar",
  },
  {
    id: "act-2",
    type: "campaign",
    title: "Campaign activated",
    description: "Sankranti Mega Sale 2026 went live",
    timestamp: hoursAgo(3),
    user: "Rajesh Kumar",
  },
  {
    id: "act-3",
    type: "media",
    title: "Media uploaded",
    description: "Ugadi Launch Video (45MB)",
    timestamp: hoursAgo(6),
    user: "Rajesh Kumar",
  },
  {
    id: "act-4",
    type: "alert",
    title: "Screen offline",
    description: "Guntur Brodipet Hub lost connection",
    timestamp: hoursAgo(48),
  },
];

export const revenueChartData = [
  { month: "Jan", revenue: 4200000, plays: 32000 },
  { month: "Feb", revenue: 4800000, plays: 38000 },
  { month: "Mar", revenue: 5200000, plays: 41000 },
  { month: "Apr", revenue: 6100000, plays: 48000 },
  { month: "May", revenue: 5800000, plays: 45000 },
  { month: "Jun", revenue: 7200000, plays: 52000 },
];

export const screenActivityData = [
  { hour: "00", online: 750, offline: 97 },
  { hour: "04", online: 710, offline: 137 },
  { hour: "08", online: 780, offline: 67 },
  { hour: "12", online: 812, offline: 35 },
  { hour: "16", online: 805, offline: 42 },
  { hour: "20", online: 798, offline: 49 },
];

export const mockPlayLogs: PlayLog[] = Array.from({ length: 20 }, (_, i) => ({
  id: `log-${i}`,
  screenId: mockScreens[i % mockScreens.length].id,
  mediaId: mockMedia[i % mockMedia.length].id,
  campaignId: mockCampaigns[i % mockCampaigns.length].id,
  playedAt: hoursAgo(i * 2),
  duration: 10 + (i % 3) * 10,
}));
